#!/bin/bash
# Script 5: simple manifesto creator

echo "Answer few questions"

read -p "Tool you use daily: " tool
read -p "Freedom means: " freedom
read -p "What you want to build: " build

date_now=$(date)
file_name="my_manifesto.txt"

echo "On $date_now, I think open source means $freedom." > $file_name
echo "I use $tool regularly and it helps me a lot." >> $file_name
echo "In future, I want to build $build and share it." >> $file_name

echo "File created: $file_name"
cat $file_name