#!/bin/bash
# Script 3: Checking folders

folders=("/etc" "/var/log" "/home" "/usr/bin" "/tmp")

echo "Folder Report"
echo "-------------"

for f in "${folders[@]}"
do
    if [ -d "$f" ]
    then
        perm=$(ls -ld $f | awk '{print $1, $3}')
        size=$(du -sh $f 2>/dev/null | cut -f1)
        
        echo "$f -> $perm | size: $size"
    else
        echo "$f not found"
    fi
done

# checking mysql folder separately
mysql_path="/etc/mysql"

if [ -d "$mysql_path" ]
then
    echo "MySQL config folder exists"
    ls -ld $mysql_path
else
    echo "MySQL config folder not found"
fi