#!/bin/bash
# Script 4: simple log checker

file=$1
word=${2:-"error"}   # default word = error
count=0

if [ ! -f "$file" ]
then
    echo "File not found"
    exit
fi

# reading file line by line
while read line
do
    echo "$line" | grep -i "$word" > /dev/null
    if [ $? -eq 0 ]
    then
        count=$((count+1))
    fi
done < "$file"

echo "Total '$word' found: $count"

echo "Last few lines:"
grep -i "$word" "$file" | tail -5